name: CI
on: ["push", "pull_request"]
jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      os: ${{ steps.set_matrix.outputs.os }}
      node_version: ${{ steps.set_matrix.outputs.node_version }}
    steps:
      - id: set_matrix
        run: |
          echo "os=['ubuntu-latest', 'macos-latest', 'windows-latest']" >> "$GITHUB_OUTPUT"
          echo "node_version=[16, 18, 20, 22, 23, 24]" >> "$GITHUB_OUTPUT"
  build-and-test:
    needs: [setup]
    strategy:
      matrix:
        os: ${{ fromJSON(needs.setup.outputs.os) }}
        node-version: ${{ fromJSON(needs.setup.outputs.node_version) }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm install
      - run: npm run build
      - run: npm run test
  mutation-test:
    needs: [build-and-test]
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '24'
          cache: 'npm'
      - run: npm install
      - name: Run mutation tests
        env:
          STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}
        run: npm run test:mutation
